### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by mocherry** [MIAnalyzer/MIA#2]
Dear Nils,

I wanted to give your application a try. However, the installation failed with the following error message after calling "miaanalyzer" from the Anaconda prompt:
File "C:\Users\kirsch\AppData\Local\Continuum\anaconda3\envs\mia_environment\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 42, in <module>
    from . import _arpack
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

What can I do?
Best,
Matthias

Also: your email-address: nils.koerber@bfr.bund.de
does not seem to work????

**Comment by nkoerb** [comment]
please see [here](https://forum.image.sc/t/installation-failed/73600)
