### ISSUE TITLE
Unable to train model on LINUX

### ISSUE THREAD

**Issue by c-chieng** [MIAnalyzer/MIA#3]
Hi Nils,

We have successfully trained a model on two Windows devices, and would like to now train the same model on Linux. After loading the settings (.json) files, we are able to see all the created classes but when "Train Model" was selected, the following error appeared. Can you please help with this?

Thank you!

Best,
Catherine
![Screenshot from 2023-06-16 14-18-17](https://github.com/MIAnalyzer/MIA/assets/136830080/51236c07-5b37-472f-8b56-f6d1796eb1a3)

**Comment by nkoerb** [comment]
Hey Catherine,

I think this error is related to an environment conflict. To get it run, you need to uninstall keras (without uninstalling tensorflow or reinstall tf-gpu). I am trying to fix the environment at the moment and hopefully will have a stable environment, soon.

Good luck!

**Comment by nkoerb** [comment]
Should be fixed with the new version
