### ISSUE TITLE
Cannot select model vit_h on SAM

### ISSUE THREAD

**Issue by ghost** [MIAnalyzer/MIA#6]
Hi @nkoerb 

Thank you very much for the new SAM feature. It's awesome.
One thing though, I could not select to install model vit_h from the drop down box. I could select and install the vit_b and vit_l, though.
Could you please check?

Thanks a lot.
![image](https://github.com/MIAnalyzer/MIA/assets/70121060/7a7c64b7-d397-47a1-ba76-8f31dbd79d5e)

**Comment by nkoerb** [comment]
Hey, well observed. The point is, github does not allow me to store files larger than 2 GB, which would be the vit-h version. I left it there as a dummy to have the option to add it when there might be an option to store it somewhere. 
However, you can check the original repo for that pretrained model: https://github.com/facebookresearch/segment-anything
Please note, downloading and using resources from external sites on your own risk.

**Comment by ghost** [comment]
Thanks for pointing out.
I note here for some one else in the future who wants to have a work around but don't know how.
1. Download the model file of vit_h from the facebook SAM github as above. Put it in C:\Users\your user name\.keras\models.
2. Edit the file youcondapath\envs\name of MIA env\lib\site-packages\mia\ui\UI.py
  Change checkable = False to True for vit_h option on line 210 (for search for "vit_h").

Restart MIA and now we can use vit_h model!
Thanks a lot for such a good tool!
